language: java
before_install:
install:
#- mvn clean install -s settings.xml -U
 - mvn clean install -s settings.xml -Ppkg=tomcat -Dservers.dir=../../../deploy/ -Ddownload
script:
notifications:
  email:
    - phamtuanchip@gmail.com
  
